language: python
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install `cat requirements.apt` -qqy
install:
  - pip install -qr test_requirements.txt
script:
  - python test.py
  - flake8 .
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
