language: python
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install `cat requirements.apt` -qqy
script:
  - make test
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
